# Generated by Django 5.2.2 on 2025-06-07 18:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('health', 'Health'), ('education', 'Education'), ('finance', 'Finance'), ('social', 'Social'), ('travel', 'Travel'), ('shopping', 'Shopping')], default='work', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timeStart', models.TimeField(default=datetime.time(9, 0))),
                ('timeEnd', models.TimeField(default=datetime.time(10, 0))),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'timeStart'],
            },
        ),
    ]
